#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure devel/patch

  case "$(uname -s)" in
    Linux)
			sudo aptitude install -y libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
      ;;
  esac

  env PYTHON=python block compile virtualenv
  ln -nfs "../vendor/virtualenv/bin/rb-site" "$shome/bin/"
}

bootstrap
