#!/usr/bin/env bash

function main {
  local shome="${_reviewboard_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$shome/vendor/virtualenv/bin/rb-site" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
